<?php
/**
 * German Language File
 * Language: German (de)
 * Used for session-based language management
 */
return [
    // ==================== HOME PAGE ====================
    // Welcome section
    'welcome' => 'Willkommen',
    'welcome_back' => 'Willkommen zurück',
    'welcome_guest' => 'Willkommen bei SpaKaas',
    'welcome_subtitle' => 'Genießen Sie reine Entspannung und Luxus',
    'welcome_intro' => 'Wir freuen uns, dass Sie in unserem luxuriösen Spa-Resort sind. Hier können Sie dem Alltag vollständig entfliehen und sich mit den besten Behandlungen verwöhnen.',

    // Features
    'premium_treatments' => 'Premium-Behandlungen',
    'premium_treatments_desc' => 'Wählen Sie aus unserem exklusiven Wellnessangebot',
    'easy_booking' => 'Einfache Buchung',
    'easy_booking_desc' => 'Reservieren Sie Ihre Lieblingsbehandlung direkt',
    'special_offers' => 'Spezielle Angebote',
    'special_offers_desc' => 'Exklusive Angebote für unsere Mitglieder',
    'vip_status' => 'VIP-Status',
    'vip_status_desc' => 'Genießen Sie zusätzliche Vorteile und Privilegien',

    // Statistics
    'availability_24_7' => '24/7',
    'availability_label' => 'Verfügbarkeit',
    'great_reviews' => 'Großartig',
    'reviews_label' => 'Bewertungen',

    // Reviews section
    'recent_reviews' => 'Aktuelle Bewertungen',
    'create_review' => 'Bewertung schreiben',
    'login_to_review' => 'Melden Sie sich an, um eine Bewertung zu schreiben',
    'rating' => 'Bewertung',
    'out_of_5' => '/5',
    'edit' => 'Bearbeiten',

    // Database/Error messages
    'db_connection_failed' => 'Datenbankverbindung fehlgeschlagen',
    'guest' => 'Gast',
    'login_link' => 'Anmelden',

    // ==================== NAVIGATION ====================
    'nav_home' => 'Startseite',
    'nav_bookings' => 'Buchungen',
    'nav_profile' => 'Profil',
    'nav_about' => 'Über uns',
    'nav_reviews' => 'Bewertungen',
    'nav_agenda' => 'Tagesordnung',
    'nav_logout' => 'Abmelden',
    'nav_login' => 'Anmelden',
    'nav_employee' => 'Mitarbeiterseite',

    // ==================== LODGES PAGE ====================
    'lodges_title' => 'Unsere Lodges',
    'lodges_description' => 'Beschreibung',
    'lodges_capacity' => 'Kapazität',
    'lodges_price' => 'Preis',
    'lodges_persons' => 'Personen',
    'lodges_book_appointment' => 'Termin vereinbaren',
    'lodges_currency' => '€',

    // ==================== LODGE PDP (Product Detail Page) ====================
    'lodge_pdp_invalid' => 'Ungültiger Lodgetyp.',
    'lodge_pdp_not_found' => 'Lodgetyp nicht gefunden.',
    'lodge_pdp_capacity_label' => 'Kapazität:',
    'lodge_pdp_capacity_unit' => 'Personen',
    'lodge_pdp_id_label' => 'Lodgetyp-ID:',
    'lodge_pdp_book_btn' => 'Termin vereinbaren',
    'lodge_pdp_favorite_btn' => 'Favorit',
    'lodge_pdp_unfavorite_btn' => 'Aus Favoriten entfernen',

    // ==================== MAKE APPOINTMENT PAGE ====================
    'appointment_title' => 'Neuen Termin hinzufügen',
    'appointment_start_time' => 'Startzeit:',
    'appointment_end_time' => 'Endzeit:',
    'appointment_description' => 'Beschreibung:',
    'appointment_select_user' => 'Benutzer auswählen:',
    'appointment_select_lodgetype' => 'Lodgetyp auswählen:',
    'appointment_select_lodgetype_placeholder' => '-- Lodgetyp auswählen --',
    'appointment_lodge_info_title' => 'Informationen der ausgewählten Lodge',
    'appointment_lodge_info_name' => 'Name:',
    'appointment_lodge_info_capacity' => 'Kapazität:',
    'appointment_lodge_info_price' => 'Preis:',
    'appointment_lodge_info_description' => 'Beschreibung:',
    'appointment_select_users' => '-- Auswählen --',
    'appointment_number_of_people' => 'Anzahl der Personen:',
    'appointment_submit_btn' => 'Hinzufügen',
    'appointment_connection_failed' => 'Verbindung fehlgeschlagen:',
    'appointment_not_logged_in' => 'Sie sind nicht angemeldet.',

    // Appointment error messages
    'appointment_error_no_user' => 'Bitte wählen Sie einen Benutzer aus.',
    'appointment_error_no_lodgetype' => 'Bitte wählen Sie einen Lodgetyp aus.',
    'appointment_error_invalid_people_count' => 'Die Anzahl der Personen muss größer als 0 sein.',
    'appointment_error_invalid_capacity' => 'Ungültiger Lodgetyp oder Kapazität nicht gefunden.',
    'appointment_error_capacity_exceeded' => 'Sie können nicht mehr als :capacity Personen für diesen Lodgetyp buchen.',
    'appointment_error_past_date' => 'Datum darf nicht in der Vergangenheit liegen.',
    'appointment_error_invalid_time' => 'Endzeit muss nach der Startzeit liegen.',
    'appointment_error_no_availability' => 'Keine verfügbare Lodge für diesen Lodgetyp in diesem Zeitraum gefunden.',
    'appointment_error_db' => 'Fehler beim Hinzufügen des Termins:',

    // Appointment success messages
    'appointment_success_title' => 'Buchungsbestätigung',
    'appointment_success_message' => 'Sehr geehrte(r) :name,

Ihr Termin wurde erfolgreich erstellt.

Details:
- Startzeit: :startTime
- Endzeit: :endTime
- Beschreibung: :description
- Anzahl der Personen: :numberOfPeople

Wir freuen uns auf Sie am vereinbarten Datum und wünschen Ihnen bereits jetzt eine schöne Zeit!',

    // ==================== PROFILE/EDIT USER PAGE ====================
    'edit_user_title' => 'Informationen aktualisieren',
    'edit_user_email' => 'E-Mail',
    'edit_user_email_required' => 'Muss eine gültige E-Mail sein',
    'edit_user_password' => 'Passwort',
    'edit_user_password_placeholder' => 'Lassen Sie das Feld leer, um nicht zu ändern',
    'edit_user_password_empty_note' => 'Lassen Sie das Feld leer, wenn Sie das Passwort nicht ändern möchten',
    'edit_user_password_invalid' => 'Das Passwort erfüllt nicht die Anforderungen.',
    'edit_user_name' => 'Name',
    'edit_user_address' => 'Adresse',
    'edit_user_postcode' => 'Postleitzahl',
    'edit_user_postcode_format' => 'Format: NNNN AA (z.B. 1234 AB)',
    'edit_user_city' => 'Stadt',
    'edit_user_phone' => 'Telefon',
    'edit_user_phone_note' => 'Mindestens 9 Ziffern',
    'edit_user_two_factor' => 'Zwei-Faktor-Authentifizierung',
    'edit_user_two_factor_no' => 'Nein',
    'edit_user_two_factor_yes' => 'Ja',
    'edit_user_save' => 'Speichern',
    'edit_user_errors_found' => 'Fehler gefunden',
    'edit_user_required_field' => 'Erforderliches Feld',

    // Password requirements
    'password_requirement_length' => 'Mindestens 8 Zeichen',
    'password_requirement_uppercase' => 'Mindestens 1 Großbuchstabe',
    'password_requirement_lowercase' => 'Mindestens 1 Kleinbuchstabe',
    'password_requirement_number' => 'Mindestens 1 Zahl',
    'password_requirement_special' => 'Mindestens 1 Sonderzeichen (!@#$%^&*)',

    // Validation messages
    'validation_required_fields' => 'Alle erforderlichen Felder müssen ausgefüllt werden (gekennzeichnet mit *)',
    'validation_invalid_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'validation_invalid_postcode' => 'Postleitzahl muss im Format NNNN AA sein (z.B. 1234 AB)',
    'validation_invalid_phone' => 'Telefonnummer muss mindestens 9 Ziffern enthalten',
    'validation_invalid_password' => 'Das Passwort erfüllt nicht alle Anforderungen',

    // Profile Picture Section
    'profile_picture_title' => 'Profilbild',
    'profile_picture_current' => 'Aktuelles Profilbild',
    'profile_picture_none' => 'Kein Profilbild hochgeladen',
    'profile_picture_select' => 'Foto auswählen',
    'profile_picture_formats' => 'Zulässige Formate: JPG, PNG, GIF (Max 5MB)',
    'profile_picture_preview_new' => 'Vorschau des neuen Fotos',
    'profile_picture_no_selected' => 'Kein Foto ausgewählt',
    'profile_picture_change' => 'Ändern',
    'profile_picture_delete' => 'Löschen',
    'profile_picture_save' => 'Speichern',
    'profile_picture_cancel' => 'Abbrechen',
    'profile_picture_delete_confirm' => 'Möchten Sie Ihr Profilbild wirklich löschen?',
    'profile_picture_error_required' => 'Bitte wählen Sie ein Foto aus',
    'profile_picture_error_too_large' => 'Datei ist zu groß. Maximal 5MB sind erlaubt.',
    'profile_picture_error_invalid_type' => 'Ungültiger Dateityp. Verwenden Sie JPG, PNG oder GIF.',

    // ==================== ABOUT US PAGE ====================
    'about_title' => 'Über SpaKaas Luxe Spa Resort',
    'about_subtitle' => 'Eine Oase der Ruhe und Erholung im Herzen der Niederlande, seit 2010',
    'about_story_heading' => '✨ Unsere Geschichte',
    'about_story_p1' => 'Das SpaKaas Luxe Spa Resort wurde 2010 mit einem einfachen, aber kraftvollen Ziel gegründet: einen heiligen Ort zu schaffen, an dem Gäste dem alltäglichen Stress vollständig entfliehen und sich selbst wiederfinden können. Unser Resort befindet sich in der wunderschönen Region Achterhoek und genießt eine einzigartige Lage inmitten natürlicher Schönheit und Ruhe.',
    'about_story_p2' => 'Aus einem kleinen Spa mit nur 5 Lodges ist ein führendes Wellness-Resort mit über 25 Luxus-Lodges geworden. Unser Erfolg basiert auf unserem unerschütterlichen Engagement für Qualität, Handwerk und Gästebetreuung.',
    'about_story_p3' => 'Wir behandeln über 15.000 Gäste pro Jahr, von denen die meisten regelmäßig zurückkommen. Dies ist der beste Beweis dafür, dass wir unsere Mission gut erfüllen: ein außergewöhnliches Spa-Erlebnis zu bieten, das transformativ und erneuernd ist.',
    'about_stat_years' => 'Jahre Erfahrung',
    'about_stat_lodges' => 'Lodges',
    'about_stat_guests' => 'Jährliche Gäste',
    'about_stat_rating' => 'Durchschnittliche Bewertung',
    'about_values_heading' => '💎 Unsere Werte',
    'about_values_intro' => 'Im SpaKaas Luxe Spa Resort werden wir von vier Kernwerten geleitet, die das Herz unseres Unternehmens bilden:',
    'about_value_nature' => 'Natürlichkeit',
    'about_value_nature_desc' => 'Wir glauben an die Kraft natürlicher Inhaltsstoffe und traditioneller Wellness-Praktiken. Alle unsere Behandlungen verwenden Bio- und umweltfreundliche Produkte.',
    'about_value_care' => 'Fürsorge',
    'about_value_care_desc' => 'Jeder Gast ist einzigartig und verdient persönliche Aufmerksamkeit. Unser Team nimmt sich Zeit, um Ihre Bedürfnisse zu verstehen und ein maßgeschneidertes Erlebnis zu schaffen.',
    'about_value_excellence' => 'Exzellenz',
    'about_value_excellence_desc' => 'Wir streben nach Perfektion in allem, was wir tun. Von unseren Therapeuten bis zu unseren Einrichtungen halten wir die höchsten Standards ein.',
    'about_value_sustainability' => 'Nachhaltigkeit',
    'about_value_sustainability_desc' => 'Wir verpflichten uns zum Umweltschutz. Unser Resort arbeitet zu 100% mit erneuerbaren Energien und verfolgt eine Null-Abfall-Politik.',
    'about_team_heading' => '👥 Unser Team',
    'about_team_intro' => 'Unser Team besteht aus über 50 qualifizierten Fachleuten, die jeweils leidenschaftlich ihr Fachgebiet lieben und sich der Gästebetreuung widmen.',
    'about_team_director' => 'Direktor & Gründer',
    'about_team_director_bio' => 'Mit über 20 Jahren Erfahrung in der Hotellerie verwirklichte Oskar die Vision von SpaKaas von Traum zu Realität.',
    'about_team_wellness' => 'Wellness-Berater',
    'about_team_wellness_bio' => 'Mit einem Ph.D. in Gesundheitswissenschaften gewährleistet Jesse, dass alle unsere Behandlungen wissenschaftlich fundiert sind.',
    'about_team_therapist' => 'Leitende Therapeutin',
    'about_team_therapist_bio' => 'Marijn trainiert und betreut unser Team von 35 Therapeuten und gewährleistet durchgehend hohe Qualität und Innovation.',
    'about_team_experience' => 'Gästeservice-Manager',
    'about_team_experience_bio' => 'Mert sorgt dafür, dass jeder Gast ein unvergessliches Erlebnis hat, von der Buchungsberatung bis zur Nachbetreuung.',
    'about_facilities_heading' => '🏛️ Unsere Einrichtungen',
    'about_facilities_intro' => 'SpaKaas verfügt über hochmoderne Einrichtungen, die für maximalen Komfort und Entspannung ausgelegt sind:',
    'about_facility_lodges' => 'Luxus-Lodges',
    'about_facility_lodges_desc' => 'Jede ausgestattet mit Massagebetten, Heizsystemen und Aroma-Diffusern',
    'about_facility_pool' => 'Spa-Pool',
    'about_facility_pool_desc' => 'Beheizter 500 m² großer Pool mit Wassertumult und Hydrotherapie-Düsen',
    'about_facility_sauna' => 'Saunakomplex',
    'about_facility_sauna_desc' => 'Vier verschiedene Saunas: finnisch, Infrarot und Dampfsauna',
    'about_facility_yoga' => 'Yoga & Meditationsstudio',
    'about_facility_yoga_desc' => 'Ruhiger Raum mit Bambus-Interieur und natürlichem Licht',
    'about_facility_lounge' => 'Wellness-Lounge',
    'about_facility_lounge_desc' => 'Entspannungsbereich mit Kamin und natürlichen Kristallen',
    'about_facility_restaurant' => 'Bio-Restaurant',
    'about_facility_restaurant_desc' => 'Farm-to-Table-Restaurant mit gesunden, biologischen Menüs',
    'about_facility_boutique' => 'Retail Boutique',
    'about_facility_boutique_desc' => 'Auswahl an Premium-Wellnessprodukte und Souvenirs',
    'about_facility_parking' => 'Parkplatz',
    'about_facility_parking_desc' => 'Kostenlos Parkplätze für über 200 Fahrzeuge',
    'about_sustainability_heading' => '🌱 Unser Nachhaltigkeitsverpflichtung',
    'about_sustainability_subheading' => 'Umweltbewusstsein in Aktion',
    'about_sustainability_intro' => 'SpaKaas ist stolz auf unsere Bemühungen, ein nachhaltiges Spa-Erlebnis zu bieten. 2018 wechselten wir zu 100% erneuerbaren Energien, und 2021 erreichten wir Kohlenstoffneutralität durch die Erfassung und Umwandlung unserer operativen Emissionen in grüne Initiativen.',
    'about_sustainability_solar' => 'Sonnenkollektoren',
    'about_sustainability_solar_desc' => '500kW Solarzellenkapazität auf unserem Dach',
    'about_sustainability_waste' => 'Null Abfall',
    'about_sustainability_waste_desc' => '95% unseres Abfalls werden recycelt oder kompostiert',
    'about_sustainability_water' => 'Wassereinsparung',
    'about_sustainability_water_desc' => 'Fortschrittliche Recycling-Systeme reduzieren den Wasserverbrauch um 40%',
    'about_sustainability_reforestation' => 'Aufforstung',
    'about_sustainability_reforestation_desc' => 'Für jede Buchungsreservierung pflanzen wir zwei Bäume',
    'about_sustainability_biodiversity' => 'Biodiversität',
    'about_sustainability_biodiversity_desc' => 'Unser Grundstück beherbergt 15 Bienenstöcke und Wildblumenwiesen',
    'about_contact_heading' => '📞 Kontaktieren Sie uns',
    'about_contact_intro' => 'Wir würden gerne von Ihnen hören! Senden Sie uns Ihre Fragen, Kommentare oder Buchungsanfragen.',
    'about_contact_location' => 'Standort',
    'about_contact_location_address' => 'Superweg 420, 6769 CP Urk, Niederlande',
    'about_contact_phone' => 'Telefonnummer',
    'about_contact_phone_number' => '+31 (0)611 365 315',
    'about_contact_email' => 'E-Mail',
    'about_contact_email_address' => 'SpaKaasBV@gmail.com',
    'about_contact_hours' => 'Öffnungszeiten',
    'about_contact_hours_value' => 'Immer geöffnet',

    // ==================== REVIEW PAGE ====================
    'review_page_title' => 'Bewertungen',
    'review_form_title_new' => 'Bewertung schreiben',
    'review_form_title_edit' => 'Bewertung bearbeiten',
    'review_form_rating' => 'Bewertung (1-5)',
    'review_form_message' => 'Nachricht',
    'review_form_illustration' => 'Abbildung (optional)',
    'review_form_submit' => 'Bewertung absenden',
    'review_form_update' => 'Bewertung aktualisieren',
    'review_form_delete' => 'Bewertung löschen',
    'review_form_delete_confirm' => 'Diese Bewertung löschen?',
    'review_login_prompt' => 'Möchten Sie eine Bewertung schreiben?',
    'review_login_required' => 'Sie müssen angemeldet sein, um eine Bewertung zu schreiben.',
    'review_login_here' => 'Hier anmelden',
    'review_create_account' => 'Konto erstellen',
    'review_success_new' => 'Bewertung erfolgreich eingereicht!',
    'review_success_update' => 'Bewertung erfolgreich aktualisiert!',
    'review_success_delete' => 'Bewertung erfolgreich gelöscht.',
    'review_error_rating' => 'Bewertung muss zwischen 1 und 5 liegen.',
    'review_error_message_empty' => 'Nachricht ist erforderlich.',
    'review_error_upload' => 'Fehler beim Hochladen der Datei.',
    'review_error_file_size' => 'Bild ist größer als 5MB.',
    'review_error_file_type' => 'Nur JPG, PNG oder GIF erlaubt.',
    'review_error_not_found' => 'Bewertung nicht gefunden oder nicht Ihre zum Bearbeiten.',
    'review_error_not_found_delete' => 'Bewertung nicht gefunden oder nicht Ihre zum Löschen.',
    'review_error_db' => 'Datenbankverbindung fehlgeschlagen',
    'review_heading_recent' => 'Aktuelle Bewertungen',
    'review_rating_label' => 'Bewertung',
    'review_edit_link' => 'Bearbeiten',

        // ==================== MY APPOINTMENTS PAGE ====================
    'my_appointments_title' => 'Meine Termine',
    'my_appointments_subtitle' => 'Sehen Sie alle Ihre Termine und öffnen Sie Details',
    'my_appointments_no_appointments' => 'Sie haben noch keine Termine.',
    'my_appointments_make_appointment' => 'Termin vereinbaren',
    'my_appointments_lodge_type' => 'Lodgetyp',
    'my_appointments_lodge_number' => 'Lodge-Nummer:',
    'my_appointments_date' => 'Datum:',
    'my_appointments_time' => 'Zeit:',
    'my_appointments_people' => 'Anzahl der Personen:',
    'my_appointments_open_planner' => 'Im Planer öffnen',
    
    // Appointment status translations
    'appointment_status_gepland' => 'Geplant',
    'appointment_status_bezig' => 'In Bearbeitung',
    'appointment_status_voltooid' => 'Abgeschlossen',
    'appointment_status_geannuleerd' => 'Abgesagt',
    'appointment_status_bevestigd' => 'Bestätigt',
    'appointment_status_verplaatst' => 'Verschoben',
    'appointment_status_niet_verschenen' => 'Nicht erschienen',
    'appointment_status_in_afwachting' => 'Ausstehend',
    'appointment_status_unknown' => 'Unbekannt',
];
?>