<?php
/**
 * French Language File
 * Language: French (fr)
 * Used for session-based language management
 */
return [
    // ==================== HOME PAGE ====================
    // Welcome section
    'welcome' => 'Bienvenue',
    'welcome_back' => 'Bienvenue de retour',
    'welcome_guest' => 'Bienvenue à SpaKaas',
    'welcome_subtitle' => 'Profitez de la pure détente et du luxe',
    'welcome_intro' => 'Nous sommes heureux que vous soyez dans notre station thermale de luxe. Ici, vous pouvez complètement échapper à la vie quotidienne et vous dorloter avec les meilleurs traitements.',

    // Features
    'premium_treatments' => 'Traitements Premium',
    'premium_treatments_desc' => 'Choisissez parmi nos offres de bien-être exclusives',
    'easy_booking' => 'Réservation Facile',
    'easy_booking_desc' => 'Réservez votre traitement préféré directement',
    'special_offers' => 'Offres Spéciales',
    'special_offers_desc' => 'Offres exclusives pour nos membres',
    'vip_status' => 'Statut VIP',
    'vip_status_desc' => 'Profitez d\'avantages et de privilèges supplémentaires',

    // Statistics
    'availability_24_7' => '24/7',
    'availability_label' => 'Disponibilité',
    'great_reviews' => 'Extraordinaire',
    'reviews_label' => 'Avis',

    // Reviews section
    'recent_reviews' => 'Avis Récents',
    'create_review' => 'Écrire un Avis',
    'login_to_review' => 'Connectez-vous pour écrire un avis',
    'rating' => 'Évaluation',
    'out_of_5' => '/5',
    'edit' => 'Modifier',

    // Database/Error messages
    'db_connection_failed' => 'Échec de la connexion à la base de données',
    'guest' => 'Invité',
    'login_link' => 'Se connecter',

    // ==================== NAVIGATION ====================
    'nav_home' => 'Accueil',
    'nav_bookings' => 'Réservations',
    'nav_profile' => 'Profil',
    'nav_about' => 'À Propos',
    'nav_reviews' => 'Avis',
    'nav_logout' => 'Déconnexion',
    'nav_login' => 'Connexion',
    'nav_employee' => 'Page Employé',

    // ==================== LODGES PAGE ====================
    'lodges_title' => 'Nos Lodges',
    'lodges_description' => 'Description',
    'lodges_capacity' => 'Capacité',
    'lodges_price' => 'Prix',
    'lodges_persons' => 'personnes',
    'lodges_book_appointment' => 'Prendre Rendez-vous',
    'lodges_currency' => '€',

    // ==================== LODGE PDP (Product Detail Page) ====================
    'lodge_pdp_invalid' => 'Type de lodge invalide.',
    'lodge_pdp_not_found' => 'Type de lodge non trouvé.',
    'lodge_pdp_capacity_label' => 'Capacité:',
    'lodge_pdp_capacity_unit' => 'personnes',
    'lodge_pdp_id_label' => 'ID du Type de Lodge:',
    'lodge_pdp_book_btn' => 'Prendre Rendez-vous',
    'lodge_pdp_favorite_btn' => 'Ajouter aux Favoris',
    'lodge_pdp_unfavorite_btn' => 'Retirer des Favoris',

    // ==================== MAKE APPOINTMENT PAGE ====================
    'appointment_title' => 'Ajouter un Nouveau Rendez-vous',
    'appointment_start_time' => 'Heure de Début:',
    'appointment_end_time' => 'Heure de Fin:',
    'appointment_description' => 'Description:',
    'appointment_select_user' => 'Sélectionner Utilisateur:',
    'appointment_select_lodgetype' => 'Sélectionner Type de Lodge:',
    'appointment_select_lodgetype_placeholder' => '-- Sélectionner Type de Lodge --',
    'appointment_lodge_info_title' => 'Informations de Lodge Sélectionnée',
    'appointment_lodge_info_name' => 'Nom:',
    'appointment_lodge_info_capacity' => 'Capacité:',
    'appointment_lodge_info_price' => 'Prix:',
    'appointment_lodge_info_description' => 'Description:',
    'appointment_select_users' => '-- Sélectionner --',
    'appointment_number_of_people' => 'Nombre de Personnes:',
    'appointment_submit_btn' => 'Ajouter',
    'appointment_connection_failed' => 'Connexion échouée:',
    'appointment_not_logged_in' => 'Vous n\'êtes pas connecté.',

    // Appointment error messages
    'appointment_error_no_user' => 'Veuillez sélectionner un utilisateur.',
    'appointment_error_no_lodgetype' => 'Veuillez sélectionner un type de lodge.',
    'appointment_error_invalid_people_count' => 'Le nombre de personnes doit être supérieur à 0.',
    'appointment_error_invalid_capacity' => 'Type de lodge invalide ou capacité non trouvée.',
    'appointment_error_capacity_exceeded' => 'Vous ne pouvez pas réserver plus de :capacity personnes pour ce type de lodge.',
    'appointment_error_past_date' => 'La date ne peut pas être dans le passé.',
    'appointment_error_invalid_time' => 'L\'heure de fin doit être après l\'heure de début.',
    'appointment_error_no_availability' => 'Aucune lodge disponible pour ce type de lodge dans cette période.',
    'appointment_error_db' => 'Erreur lors de l\'ajout du rendez-vous:',

    // Appointment success messages
    'appointment_success_title' => 'Confirmation de Réservation',
    'appointment_success_message' => 'Chère :name,

Votre rendez-vous a été créé avec succès.

Détails:
- Heure de Début: :startTime
- Heure de Fin: :endTime
- Description: :description
- Nombre de Personnes: :numberOfPeople

Nous vous attendons à la date prévue et vous souhaitons une excellente visite!',

    // ==================== PROFILE/EDIT USER PAGE ====================
    'edit_user_title' => 'Mettre à jour les Informations',
    'edit_user_email' => 'Email',
    'edit_user_email_required' => 'Doit être un email valide',
    'edit_user_password' => 'Mot de passe',
    'edit_user_password_placeholder' => 'Laissez vide pour ne pas modifier',
    'edit_user_password_empty_note' => 'Laissez vide si vous ne souhaitez pas modifier le mot de passe',
    'edit_user_password_invalid' => 'Le mot de passe ne répond pas aux exigences.',
    'edit_user_name' => 'Nom',
    'edit_user_address' => 'Adresse',
    'edit_user_postcode' => 'Code Postal',
    'edit_user_postcode_format' => 'Format: NNNN AA (ex: 1234 AB)',
    'edit_user_city' => 'Ville',
    'edit_user_phone' => 'Téléphone',
    'edit_user_phone_note' => 'Minimum 9 chiffres',
    'edit_user_two_factor' => 'Authentification à Deux Facteurs',
    'edit_user_two_factor_no' => 'Non',
    'edit_user_two_factor_yes' => 'Oui',
    'edit_user_save' => 'Enregistrer',
    'edit_user_errors_found' => 'Erreurs Trouvées',
    'edit_user_required_field' => 'Champ obligatoire',

    // Password requirements
    'password_requirement_length' => 'Au moins 8 caractères',
    'password_requirement_uppercase' => 'Au moins 1 lettre majuscule',
    'password_requirement_lowercase' => 'Au moins 1 lettre minuscule',
    'password_requirement_number' => 'Au moins 1 chiffre',
    'password_requirement_special' => 'Au moins 1 caractère spécial (!@#$%^&*)',

    // Validation messages
    'validation_required_fields' => 'Tous les champs obligatoires doivent être remplis (marqués avec *)',
    'validation_invalid_email' => 'Veuillez entrer une adresse email valide',
    'validation_invalid_postcode' => 'Le code postal doit être au format NNNN AA (ex: 1234 AB)',
    'validation_invalid_phone' => 'Le numéro de téléphone doit contenir au moins 9 chiffres',
    'validation_invalid_password' => 'Le mot de passe ne répond pas à toutes les exigences',

    // Profile Picture Section
    'profile_picture_title' => 'Photo de Profil',
    'profile_picture_current' => 'Photo de Profil Actuelle',
    'profile_picture_none' => 'Aucune photo de profil chargée',
    'profile_picture_select' => 'Sélectionner une photo',
    'profile_picture_formats' => 'Formats autorisés: JPG, PNG, GIF (Max 5MB)',
    'profile_picture_preview_new' => 'Aperçu de la nouvelle photo',
    'profile_picture_no_selected' => 'Aucune photo sélectionnée',
    'profile_picture_change' => 'Modifier',
    'profile_picture_delete' => 'Supprimer',
    'profile_picture_save' => 'Enregistrer',
    'profile_picture_cancel' => 'Annuler',
    'profile_picture_delete_confirm' => 'Êtes-vous sûr de vouloir supprimer votre photo de profil?',
    'profile_picture_error_required' => 'Veuillez sélectionner une photo',
    'profile_picture_error_too_large' => 'Le fichier est trop volumineux. Maximum 5MB autorisé.',
    'profile_picture_error_invalid_type' => 'Type de fichier invalide. Utilisez JPG, PNG ou GIF.',

    // ==================== ABOUT US PAGE ====================
    'about_title' => 'À Propos de SpaKaas Luxe Spa Resort',
    'about_subtitle' => 'Une oasis de repos et de rajeunissement au cœur des Pays-Bas, depuis 2010',
    'about_story_heading' => '✨ Notre Histoire',
    'about_story_p1' => 'SpaKaas Luxe Spa Resort a été fondée en 2010 avec un objectif simple mais puissant: créer un lieu sacré où les clients peuvent complètement échapper au stress quotidien et se redécouvrir. Situé dans la belle région d\'Achterhoek, notre station bénéficie d\'un emplacement unique entouré par la beauté naturelle et la sérénité.',
    'about_story_p2' => 'Ce qui a commencé par un petit spa avec seulement 5 lodges s\'est transformé en une station thermale de premier plan avec plus de 25 lodges de luxe. Notre succès est basé sur notre engagement inébranlable envers la qualité, l\'artisanat et le service clientèle.',
    'about_story_p3' => 'Nous accueillons plus de 15 000 clients par an, dont la majorité revient régulièrement. C\'est la meilleure preuve que nous remplissons bien notre mission: offrir une expérience spa exceptionnelle qui est transformatrice et régénérante.',
    'about_stat_years' => 'Années d\'Expérience',
    'about_stat_lodges' => 'Lodges',
    'about_stat_guests' => 'Clients Annuels',
    'about_stat_rating' => 'Note Moyenne',
    'about_values_heading' => '💎 Nos Valeurs',
    'about_values_intro' => 'À SpaKaas Luxe Spa Resort, nous sommes guidés par quatre valeurs fondamentales qui forment le cœur de notre entreprise:',
    'about_value_nature' => 'Naturalité',
    'about_value_nature_desc' => 'Nous croyons à la puissance des ingrédients naturels et des pratiques de bien-être traditionnelles. Tous nos traitements utilisent des produits biologiques et respectueux de l\'environnement.',
    'about_value_care' => 'Soin',
    'about_value_care_desc' => 'Chaque client est unique et mérite une attention personnelle. Notre équipe prend le temps de comprendre vos besoins et de créer une expérience personnalisée.',
    'about_value_excellence' => 'Excellence',
    'about_value_excellence_desc' => 'Nous nous efforçons de la perfection dans tout ce que nous faisons. De nos thérapeutes à nos installations, nous maintenons les normes les plus élevées.',
    'about_value_sustainability' => 'Durabilité',
    'about_value_sustainability_desc' => 'Nous nous engageons pour l\'environnement. Notre station fonctionne à 100% sur l\'énergie renouvelable et maintient une politique de zéro déchet.',
    'about_team_heading' => '👥 Notre Équipe',
    'about_team_intro' => 'Notre équipe se compose de plus de 50 professionnels qualifiés, chacun passionné par son domaine et dévoué au service client.',
    'about_team_director' => 'Directeur & Fondateur',
    'about_team_director_bio' => 'Avec plus de 20 ans d\'expérience dans l\'industrie hôtelière, Oskar a réalisé la vision de SpaKaas du rêve à la réalité.',
    'about_team_wellness' => 'Conseiller en Bien-être',
    'about_team_wellness_bio' => 'Titulaire d\'un doctorat en sciences de la santé, Jesse s\'assure que tous nos traitements sont scientifiquement fondés.',
    'about_team_therapist' => 'Thérapeute en Chef',
    'about_team_therapist_bio' => 'Marijn forme et encadre notre équipe de 35 thérapeutes, assurant une qualité et une innovation constamment élevées.',
    'about_team_experience' => 'Gestionnaire de l\'Expérience Client',
    'about_team_experience_bio' => 'Mert s\'assure que chaque client a une expérience inoubliable, de l\'orientation de la réservation aux soins de suivi.',
    'about_facilities_heading' => '🏛️ Nos Installations',
    'about_facilities_intro' => 'SpaKaas dispose d\'installations à la pointe de la technologie conçues pour un confort et une détente maximums:',
    'about_facility_lodges' => 'Lodges de Luxe',
    'about_facility_lodges_desc' => 'Chacun équipé de lits de massage, systèmes de chauffage et diffuseurs d\'arôme',
    'about_facility_pool' => 'Piscine Spa',
    'about_facility_pool_desc' => 'Piscine chauffée de 500 m² avec courants d\'eau et jets d\'hydrothérapie',
    'about_facility_sauna' => 'Complexe de Sauna',
    'about_facility_sauna_desc' => 'Quatre saunas différents incluant sauna finlandais, infrarouge et vapeur',
    'about_facility_yoga' => 'Studio de Yoga & Méditation',
    'about_facility_yoga_desc' => 'Espace serein avec intérieur en bambou et lumière naturelle',
    'about_facility_lounge' => 'Salon de Bien-être',
    'about_facility_lounge_desc' => 'Espace de détente avec foyer et cristaux naturels',
    'about_facility_restaurant' => 'Restaurant Biologique',
    'about_facility_restaurant_desc' => 'Restaurant à la ferme avec menus sains et biologiques',
    'about_facility_boutique' => 'Boutique de Détail',
    'about_facility_boutique_desc' => 'Sélection de produits de bien-être premium et souvenirs',
    'about_facility_parking' => 'Stationnement',
    'about_facility_parking_desc' => 'Stationnement gratuit pour 200+ véhicules',
    'about_sustainability_heading' => '🌱 Notre Engagement Envers la Durabilité',
    'about_sustainability_subheading' => 'Conscience Environnementale en Action',
    'about_sustainability_intro' => 'SpaKaas est fière de nos efforts pour fournir une expérience spa durable. En 2018, nous avons transitionné vers 100% d\'énergie renouvelable, et en 2021, nous avons atteint la neutralité carbone en capturant et en convertissant nos émissions opérationnelles en initiatives vertes.',
    'about_sustainability_solar' => 'Panneaux Solaires',
    'about_sustainability_solar_desc' => 'Capacité de panneau solaire de 500kW sur notre toit',
    'about_sustainability_waste' => 'Zéro Déchet',
    'about_sustainability_waste_desc' => '95% de nos déchets sont recyclés ou compostés',
    'about_sustainability_water' => 'Économie d\'Eau',
    'about_sustainability_water_desc' => 'Les systèmes de recyclage avancés réduisent la consommation d\'eau de 40%',
    'about_sustainability_reforestation' => 'Reboisement',
    'about_sustainability_reforestation_desc' => 'Pour chaque réservation, nous plantons deux arbres',
    'about_sustainability_biodiversity' => 'Biodiversité',
    'about_sustainability_biodiversity_desc' => 'Notre propriété abrite 15 ruches et des prairies de fleurs sauvages',
    'about_contact_heading' => '📞 Nous Contacter',
    'about_contact_intro' => 'Nous aimerions avoir de vos nouvelles! Envoyez-nous vos questions, commentaires ou demandes de réservation.',
    'about_contact_location' => 'Localisation',
    'about_contact_location_address' => 'Superweg 420, 6769 CP Urk, Pays-Bas',
    'about_contact_phone' => 'Numéro de Téléphone',
    'about_contact_phone_number' => '+31 (0)611 365 315',
    'about_contact_email' => 'Email',
    'about_contact_email_address' => 'SpaKaasBV@gmail.com',
    'about_contact_hours' => 'Heures d\'Ouverture',
    'about_contact_hours_value' => 'Toujours Ouvert',

    // ==================== REVIEW PAGE ====================
    'review_page_title' => 'Avis',
    'review_form_title_new' => 'Écrire un Avis',
    'review_form_title_edit' => 'Modifier l\'Avis',
    'review_form_rating' => 'Évaluation (1-5)',
    'review_form_message' => 'Message',
    'review_form_illustration' => 'Illustration (optionnel)',
    'review_form_submit' => 'Soumettre l\'Avis',
    'review_form_update' => 'Mettre à jour l\'Avis',
    'review_form_delete' => 'Supprimer l\'Avis',
    'review_form_delete_confirm' => 'Supprimer cet avis?',
    'review_login_prompt' => 'Vous voulez écrire un avis?',
    'review_login_required' => 'Vous devez être connecté pour écrire un avis.',
    'review_login_here' => 'Se connecter ici',
    'review_create_account' => 'créer un compte',
    'review_success_new' => 'Avis soumis avec succès!',
    'review_success_update' => 'Avis mis à jour avec succès!',
    'review_success_delete' => 'Avis supprimé avec succès.',
    'review_error_rating' => 'L\'évaluation doit être entre 1 et 5.',
    'review_error_message_empty' => 'Le message est obligatoire.',
    'review_error_upload' => 'Erreur lors du téléchargement du fichier.',
    'review_error_file_size' => 'L\'image est plus grande que 5MB.',
    'review_error_file_type' => 'Seuls JPG, PNG ou GIF sont autorisés.',
    'review_error_not_found' => 'Avis introuvable ou pas le vôtre à modifier.',
    'review_error_not_found_delete' => 'Avis introuvable ou pas le vôtre à supprimer.',
    'review_error_db' => 'Échec de la connexion à la base de données',
    'review_heading_recent' => 'Avis Récents',
    'review_rating_label' => 'Évaluation',
    'review_edit_link' => 'Modifier',

        // ==================== MY APPOINTMENTS PAGE ====================
    'my_appointments_title' => 'Mes Rendez-vous',
    'my_appointments_subtitle' => 'Consultez tous vos rendez-vous et ouvrez les détails',
    'my_appointments_no_appointments' => 'Vous n\'avez pas encore de rendez-vous.',
    'my_appointments_make_appointment' => 'Prendre un rendez-vous',
    'my_appointments_lodge_type' => 'Type de Lodge',
    'my_appointments_lodge_number' => 'Numéro de Lodge:',
    'my_appointments_date' => 'Date:',
    'my_appointments_time' => 'Heure:',
    'my_appointments_people' => 'Nombre de Personnes:',
    'my_appointments_open_planner' => 'Ouvrir dans le planificateur',
    
    // Appointment status translations
    'appointment_status_gepland' => 'Planifié',
    'appointment_status_bezig' => 'En Cours',
    'appointment_status_voltooid' => 'Terminé',
    'appointment_status_geannuleerd' => 'Annulé',
    'appointment_status_bevestigd' => 'Confirmé',
    'appointment_status_verplaatst' => 'Replanifié',
    'appointment_status_niet_verschenen' => 'Non Venu',
    'appointment_status_in_afwachting' => 'En Attente',
    'appointment_status_unknown' => 'Inconnu',
];
?>