<?php
/**
 * Turkish Language File
 * Language: Turkish (tr)
 * Used for session-based language management
 */
return [
    // ==================== HOME PAGE ====================
    // Welcome section
    'welcome' => 'Hoş Geldiniz',
    'welcome_back' => 'Tekrar Hoş Geldiniz',
    'welcome_guest' => 'SpaKaas\'a Hoş Geldiniz',
    'welcome_subtitle' => 'Saf rahatlama ve lüksün tadını çıkartın',
    'welcome_intro' => 'Lüks Spa Rezortumuzda bulunduğunuz için mutluyuz. Burada günlük hayattan tamamen kaçabilir ve en iyi tedavilerle kendinizi şımartan edebilirsiniz.',

    // Features
    'premium_treatments' => 'Premium Tedaviler',
    'premium_treatments_desc' => 'Özel wellness sunumlarımızdan seçim yapın',
    'easy_booking' => 'Kolay Rezervasyon',
    'easy_booking_desc' => 'Favori tedavinizi direkt rezerve edin',
    'special_offers' => 'Özel Teklifler',
    'special_offers_desc' => 'Üyelerimiz için özel fırsatlar',
    'vip_status' => 'VIP Statüsü',
    'vip_status_desc' => 'Ekstra avantajlar ve ayrıcalıklardan yararlanın',

    // Statistics
    'availability_24_7' => '24/7',
    'availability_label' => 'Uygunluk',
    'great_reviews' => 'Harika',
    'reviews_label' => 'Yorumlar',

    // Reviews section
    'recent_reviews' => 'Son Yorumlar',
    'create_review' => 'Yorum Yazın',
    'login_to_review' => 'Yorum yazmak için giriş yapın',
    'rating' => 'Değerlendirme',
    'out_of_5' => '/5',
    'edit' => 'Düzenle',

    // Database/Error messages
    'db_connection_failed' => 'Veritabanı bağlantısı başarısız',
    'guest' => 'Misafir',
    'login_link' => 'Giriş Yap',

    // ==================== NAVIGATION ====================
    'nav_home' => 'Ana Sayfa',
    'nav_bookings' => 'Rezervasyonlar',
    'nav_profile' => 'Profil',
    'nav_about' => 'Hakkımızda',
    'nav_reviews' => 'Yorumlar',
    'nav_agenda' => 'Takvim',
    'nav_logout' => 'Çıkış Yap',
    'nav_login' => 'Giriş Yap',
    'nav_employee' => 'Çalışan Sayfası',

    // ==================== LODGES PAGE ====================
    'lodges_title' => 'Kulübelerimiz',
    'lodges_description' => 'Açıklama',
    'lodges_capacity' => 'Kapasite',
    'lodges_price' => 'Fiyat',
    'lodges_persons' => 'kişi',
    'lodges_book_appointment' => 'Randevu Alın',
    'lodges_currency' => '€',

    // ==================== LODGE PDP (Product Detail Page) ====================
    'lodge_pdp_invalid' => 'Geçersiz lodge türü.',
    'lodge_pdp_not_found' => 'Lodge türü bulunamadı.',
    'lodge_pdp_capacity_label' => 'Kapasite:',
    'lodge_pdp_capacity_unit' => 'kişi',
    'lodge_pdp_id_label' => 'Lodge Türü ID:',
    'lodge_pdp_book_btn' => 'Randevu Alın',
    'lodge_pdp_favorite_btn' => 'Favorilere Ekle',
    'lodge_pdp_unfavorite_btn' => 'Favorilerden Çıkar',

    // ==================== MAKE APPOINTMENT PAGE ====================
    'appointment_title' => 'Yeni Randevu Ekle',
    'appointment_start_time' => 'Başlangıç Saati:',
    'appointment_end_time' => 'Bitiş Saati:',
    'appointment_description' => 'Açıklama:',
    'appointment_select_user' => 'Kullanıcı Seçin:',
    'appointment_select_lodgetype' => 'Lodge Türü Seçin:',
    'appointment_select_lodgetype_placeholder' => '-- Lodge Türü Seçin --',
    'appointment_lodge_info_title' => 'Seçilen Lodge Bilgileri',
    'appointment_lodge_info_name' => 'Ad:',
    'appointment_lodge_info_capacity' => 'Kapasite:',
    'appointment_lodge_info_price' => 'Fiyat:',
    'appointment_lodge_info_description' => 'Açıklama:',
    'appointment_select_users' => '-- Seçin --',
    'appointment_number_of_people' => 'Kişi Sayısı:',
    'appointment_submit_btn' => 'Ekle',
    'appointment_connection_failed' => 'Bağlantı başarısız:',
    'appointment_not_logged_in' => 'Giriş yapmadınız.',

    // Appointment error messages
    'appointment_error_no_user' => 'Lütfen bir kullanıcı seçin.',
    'appointment_error_no_lodgetype' => 'Lütfen bir lodge türü seçin.',
    'appointment_error_invalid_people_count' => 'Kişi sayısı 0\'dan büyük olmalıdır.',
    'appointment_error_invalid_capacity' => 'Geçersiz lodge türü veya kapasite bulunamadı.',
    'appointment_error_capacity_exceeded' => 'Bu lodge türü için :capacity kişiden fazla rezervasyon yapamazsınız.',
    'appointment_error_past_date' => 'Tarih geçmişte olamaz.',
    'appointment_error_invalid_time' => 'Bitiş saati başlangıç saatinden sonra olmalıdır.',
    'appointment_error_no_availability' => 'Bu dönem için bu lodge türüne uygun lodge bulunamadı.',
    'appointment_error_db' => 'Randevu eklenirken hata:',

    // Appointment success messages
    'appointment_success_title' => 'Rezervasyon Onayı',
    'appointment_success_message' => 'Sayın :name,

Randevunuz başarıyla oluşturulmuştur.

Detaylar:
- Başlangıç Saati: :startTime
- Bitiş Saati: :endTime
- Açıklama: :description
- Kişi Sayısı: :numberOfPeople

Sizi belirlenen tarihte görmeyi dört gözle bekliyoruz ve şimdiden güzel bir zaman geçirmenizi diliyoruz!',

    // ==================== PROFILE/EDIT USER PAGE ====================
    'edit_user_title' => 'Bilgileri Güncelle',
    'edit_user_email' => 'E-posta',
    'edit_user_email_required' => 'Geçerli bir e-posta olmalı',
    'edit_user_password' => 'Şifre',
    'edit_user_password_placeholder' => 'Değiştirmemek için boş bırakın',
    'edit_user_password_empty_note' => 'Şifreyi değiştirmek istemiyorsanız boş bırakın',
    'edit_user_password_invalid' => 'Şifre gerekli şartları karşılamıyor.',
    'edit_user_name' => 'Ad',
    'edit_user_address' => 'Adres',
    'edit_user_postcode' => 'Posta Kodu',
    'edit_user_postcode_format' => 'Format: NNNN AA (ör. 1234 AB)',
    'edit_user_city' => 'Şehir',
    'edit_user_phone' => 'Telefon',
    'edit_user_phone_note' => 'En az 9 haneli',
    'edit_user_two_factor' => 'İki Faktörlü Kimlik Doğrulama',
    'edit_user_two_factor_no' => 'Hayır',
    'edit_user_two_factor_yes' => 'Evet',
    'edit_user_save' => 'Kaydet',
    'edit_user_errors_found' => 'Hatalar Bulundu',
    'edit_user_required_field' => 'Gerekli alan',

    // Password requirements
    'password_requirement_length' => 'En az 8 karakter',
    'password_requirement_uppercase' => 'En az 1 büyük harf',
    'password_requirement_lowercase' => 'En az 1 küçük harf',
    'password_requirement_number' => 'En az 1 sayı',
    'password_requirement_special' => 'En az 1 özel karakter (!@#$%^&*)',

    // Validation messages
    'validation_required_fields' => 'Tüm gerekli alanlar doldurulmalıdır (* ile işaretli)',
    'validation_invalid_email' => 'Lütfen geçerli bir e-posta adresi girin',
    'validation_invalid_postcode' => 'Posta kodu NNNN AA formatında olmalıdır (ör. 1234 AB)',
    'validation_invalid_phone' => 'Telefon numarası en az 9 haneli olmalıdır',
    'validation_invalid_password' => 'Şifre tüm şartları karşılamıyor',

    // Profile Picture Section
    'profile_picture_title' => 'Profil Resmi',
    'profile_picture_current' => 'Mevcut Profil Resmi',
    'profile_picture_none' => 'Profil resmi yüklenmemiş',
    'profile_picture_select' => 'Fotoğraf seçin',
    'profile_picture_formats' => 'İzin verilen formatlar: JPG, PNG, GIF (Max 5MB)',
    'profile_picture_preview_new' => 'Yeni fotoğraf önizlemesi',
    'profile_picture_no_selected' => 'Fotoğraf seçilmedi',
    'profile_picture_change' => 'Değiştir',
    'profile_picture_delete' => 'Sil',
    'profile_picture_save' => 'Kaydet',
    'profile_picture_cancel' => 'İptal',
    'profile_picture_delete_confirm' => 'Profil resminizi silmek istediğinize emin misiniz?',
    'profile_picture_error_required' => 'Lütfen bir fotoğraf seçin',
    'profile_picture_error_too_large' => 'Dosya çok büyük. Maksimum 5MB\'ye izin verilir.',
    'profile_picture_error_invalid_type' => 'Geçersiz dosya türü. JPG, PNG veya GIF kullanın.',

    // ==================== ABOUT US PAGE ====================
    'about_title' => 'SpaKaas Lüks Spa Rezortu Hakkında',
    'about_subtitle' => 'Hollanda\'nın kalbinde dinlenme ve yenileme oası, 2010\'dan beri',
    'about_story_heading' => '✨ Bizim Hikayemiz',
    'about_story_p1' => 'SpaKaas Lüks Spa Rezortu 2010 yılında basit ama güçlü bir hedefle kurulmuştur: misafirlerin günlük stresden tamamen kaçabilecekleri ve kendilerini yeniden keşfedebilecekleri kutsal bir yer oluşturmak. Güzel Achterhoek bölgesinde bulunan rezortumuz, doğal güzellik ve huzur içinde eşsiz bir konumdan faydalanmaktadır.',
    'about_story_p2' => 'Yalnızca 5 kulübesi olan küçük bir spa ile başlayan, 25\'ten fazla lüks kulübeyi olan önde gelen bir wellness rezortuna dönüşmüştür. Başarımız kalite, zanaat ve misafir hizmetine karşı sarsılmaz taahhüdümüze dayanmaktadır.',
    'about_story_p3' => 'Yılda 15.000\'den fazla misafiri ağırlarız ve çoğu düzenli olarak geri gelir. Bu, görevimizi iyi yerine getirdiğimizin en iyi kanıtıdır: dönüştürücü ve yenileyici bir spa deneyimi sunmak.',
    'about_stat_years' => 'Deneyim Yılı',
    'about_stat_lodges' => 'Kulübe',
    'about_stat_guests' => 'Yıllık Misafir',
    'about_stat_rating' => 'Ortalama Derecelendirme',
    'about_values_heading' => '💎 Bizim Değerlerimiz',
    'about_values_intro' => 'SpaKaas Lüks Spa Rezortunda, işimizin kalbini oluşturan dört temel değer tarafından yönlendiriliyoruz:',
    'about_value_nature' => 'Doğallık',
    'about_value_nature_desc' => 'Doğal bileşenlerin ve geleneksel wellness uygulamalarının gücüne inanıyoruz. Tüm tedavilerimiz organik ve çevre dostu ürünleri kullanmaktadır.',
    'about_value_care' => 'Bakım',
    'about_value_care_desc' => 'Her misafir benzersizdir ve kişisel dikkat hak etmektedir. Ekibimiz ihtiyaçlarınızı anlamak ve kişiselleştirilmiş bir deneyim oluşturmak için zaman ayırır.',
    'about_value_excellence' => 'Mükemmellik',
    'about_value_excellence_desc' => 'Yaptığımız her şeyde mükemmeliyeti hedefliyoruz. Terapistlerimizden tesislerimize kadar en yüksek standartları koruyu.',
    'about_value_sustainability' => 'Sürdürülebilirlik',
    'about_value_sustainability_desc' => 'Çevreye karşı taahhütlüyüz. Rezortumuz %100 yenilenebilir enerjide çalışır ve sıfır atık politikası uygulamaktadır.',
    'about_team_heading' => '👥 Ekibimiz',
    'about_team_intro' => 'Ekibimiz 50\'den fazla nitelikli profesyonelden oluşur ve her biri alanında tutkulu ve misafir hizmetine bağlıdır.',
    'about_team_director' => 'Müdür & Kurucu',
    'about_team_director_bio' => 'Otelcilik endüstrisinde 20 yıldan fazla deneyime sahip Oskar, SpaKaas vizyonunu rüyadan gerçeğe dönüştürdü.',
    'about_team_wellness' => 'Wellness Danışmanı',
    'about_team_wellness_bio' => 'Sağlık bilimleri alanında doktora derecesine sahip Jesse, tüm tedavilerimizin bilimsel olarak sağlam olmasını sağlar.',
    'about_team_therapist' => 'Baş Terapist',
    'about_team_therapist_bio' => 'Marijn, 35 terapistten oluşan ekibimizi eğitir ve yönetir, tutarlı yüksek kalite ve inovasyonu sağlar.',
    'about_team_experience' => 'Misafir Deneyimi Yöneticisi',
    'about_team_experience_bio' => 'Mert, her misafirin rezervasyon rehberliğinden takip bakımına kadar unutulmaz bir deneyim yaşamasını sağlar.',
    'about_facilities_heading' => '🏛️ Tesislerimiz',
    'about_facilities_intro' => 'SpaKaas, maksimum konfor ve rahatlama için tasarlanmış son teknoloji tesis ve tesislerdir:',
    'about_facility_lodges' => 'Lüks Kulübeler',
    'about_facility_lodges_desc' => 'Her biri masaj yatakları, ısıtma sistemleri ve aroma difüzörleri ile donatılmıştır',
    'about_facility_pool' => 'Spa Havuzu',
    'about_facility_pool_desc' => 'Su akımları ve hidroterapi jetli 500m² ısıtmalı havuz',
    'about_facility_sauna' => 'Sauna Kompleksi',
    'about_facility_sauna_desc' => 'Finlandiya, infrared ve buhar saunası dahil dört farklı sauna',
    'about_facility_yoga' => 'Yoga & Meditasyon Stüdyosu',
    'about_facility_yoga_desc' => 'Bambu iç mekan ve doğal ışık ile sakin alan',
    'about_facility_lounge' => 'Wellness Lounge',
    'about_facility_lounge_desc' => 'Şömine ve doğal kristallerle rahatlatma alanı',
    'about_facility_restaurant' => 'Organik Restoran',
    'about_facility_restaurant_desc' => 'Sağlıklı, organik menülerle çiftlikten masaya restoran',
    'about_facility_boutique' => 'Retail Butik',
    'about_facility_boutique_desc' => 'Premium wellness ürünleri ve hediyeliklerin seçimi',
    'about_facility_parking' => 'Otopark',
    'about_facility_parking_desc' => '200+ araç için ücretsiz otopark',
    'about_sustainability_heading' => '🌱 Bizim Sürdürülebilirlik Taahhüdü',
    'about_sustainability_subheading' => 'Çevre Bilinci Eyleme Geçirilmiş',
    'about_sustainability_intro' => 'SpaKaas, sürdürülebilir bir spa deneyimi sağlamak için yaptığımız çabaları gururla sunarız. 2018 yılında %100 yenilenebilir enerjiye geçtik ve 2021 yılında operasyonel emisyonlarımızı yeşil girişimlere dönüştürerek karbon nötr duruma ulaştık.',
    'about_sustainability_solar' => 'Güneş Panelleri',
    'about_sustainability_solar_desc' => 'Çatımızda 500kW güneş paneli kapasitesi',
    'about_sustainability_waste' => 'Sıfır Atık',
    'about_sustainability_waste_desc' => 'Atığımızın %95\'i geri dönüştürülür veya kompost yapılır',
    'about_sustainability_water' => 'Su Tasarrufu',
    'about_sustainability_water_desc' => 'İleri geri dönüşüm sistemleri su tüketimini %40 azaltır',
    'about_sustainability_reforestation' => 'Ağaçlandırma',
    'about_sustainability_reforestation_desc' => 'Her rezervasyon için iki ağaç diktik',
    'about_sustainability_biodiversity' => 'Biyolojik Çeşitlilik',
    'about_sustainability_biodiversity_desc' => 'Mülkümüzde 15 arı kovanı ve yabani çiçek çayırları bulunmaktadır',
    'about_contact_heading' => '📞 Bizimle İletişime Geçin',
    'about_contact_intro' => 'Sizden haber almaktan memnun oluruz! Sorularınız, yorumlarınız veya rezervasyon isteklerinizi bize gönderin.',
    'about_contact_location' => 'Konum',
    'about_contact_location_address' => 'Superweg 420, 6769 CP Urk, Hollanda',
    'about_contact_phone' => 'Telefon Numarası',
    'about_contact_phone_number' => '+31 (0)611 365 315',
    'about_contact_email' => 'E-posta',
    'about_contact_email_address' => 'SpaKaasBV@gmail.com',
    'about_contact_hours' => 'Açılış Saatleri',
    'about_contact_hours_value' => 'Her Zaman Açık',

    // ==================== REVIEW PAGE ====================
    'review_page_title' => 'Yorumlar',
    'review_form_title_new' => 'Yorum Yazın',
    'review_form_title_edit' => 'Yorumu Düzenle',
    'review_form_rating' => 'Değerlendirme (1-5)',
    'review_form_message' => 'Mesaj',
    'review_form_illustration' => 'Resim (isteğe bağlı)',
    'review_form_submit' => 'Yorumu Gönder',
    'review_form_update' => 'Yorumu Güncelle',
    'review_form_delete' => 'Yorumu Sil',
    'review_form_delete_confirm' => 'Bu yorumu silmek istediğinize emin misiniz?',
    'review_login_prompt' => 'Yorum yazmak ister misiniz?',
    'review_login_required' => 'Yorum yazmak için giriş yapmanız gerekir.',
    'review_login_here' => 'Buradan giriş yapın',
    'review_create_account' => 'hesap oluşturun',
    'review_success_new' => 'Yorum başarıyla gönderildi!',
    'review_success_update' => 'Yorum başarıyla güncellendi!',
    'review_success_delete' => 'Yorum başarıyla silindi.',
    'review_error_rating' => 'Değerlendirme 1 ile 5 arasında olmalıdır.',
    'review_error_message_empty' => 'Mesaj gereklidir.',
    'review_error_upload' => 'Dosya yükleme hatası.',
    'review_error_file_size' => 'Resim 5MB\'den büyük.',
    'review_error_file_type' => 'Yalnızca JPG, PNG veya GIF izin verilir.',
    'review_error_not_found' => 'Yorum bulunamadı veya düzenlemek için sizin değildir.',
    'review_error_not_found_delete' => 'Yorum bulunamadı veya silmek için sizin değildir.',
    'review_error_db' => 'Veritabanı bağlantısı başarısız',
    'review_heading_recent' => 'Son Yorumlar',
    'review_rating_label' => 'Değerlendirme',
    'review_edit_link' => 'Düzenle',

        // ==================== MY APPOINTMENTS PAGE ====================
    'my_appointments_title' => 'Benim Randevularım',
    'my_appointments_subtitle' => 'Tüm randevularınızı görüntüleyin ve detayları açın',
    'my_appointments_no_appointments' => 'Henüz herhangi bir randevunuz yok.',
    'my_appointments_make_appointment' => 'Randevu alın',
    'my_appointments_lodge_type' => 'Lodge Türü',
    'my_appointments_lodge_number' => 'Lodge Numarası:',
    'my_appointments_date' => 'Tarih:',
    'my_appointments_time' => 'Saat:',
    'my_appointments_people' => 'Kişi Sayısı:',
    'my_appointments_open_planner' => 'Planlayıcıda Aç',
    
    // Appointment status translations
    'appointment_status_gepland' => 'Planlandı',
    'appointment_status_bezig' => 'Devam Ediyor',
    'appointment_status_voltooid' => 'Tamamlandı',
    'appointment_status_geannuleerd' => 'İptal Edildi',
    'appointment_status_bevestigd' => 'Onaylandı',
    'appointment_status_verplaatst' => 'Yeniden Planlandı',
    'appointment_status_niet_verschenen' => 'Gelmedi',
    'appointment_status_in_afwachting' => 'Beklemede',
    'appointment_status_unknown' => 'Bilinmiyor',
];
?>